@startuml
'https://plantuml.com/sequence-diagram

title hrslogin
actor User as user

participant "权限服务" as authserv
participant "hrs服务" as hrsserv
database "Redis" as redis

autonumber
user->authserv: 用户客户端向权限服务发起请求获取授权
activate authserv
authserv-->user: 返回token验证信息
user->hrsserv: 客户端携带token信息，调用hrs登录接口
activate hrsserv
hrsserv->authserv: hrs向权限服务checkToken是否通过
authserv-->hrsserv: 返回验证结果，user信息及相关权限原子信息
deactivate authserv
hrsserv->redis: 保存处理好的权限信息
hrsserv-->user: 返回token及权限信息
user->hrsserv: 调用其他服务接口
hrsserv->authserv: 验证是否过期
activate authserv
authserv-->hrsserv: 返回验证结果
deactivate authserv
hrsserv->redis: 验证token信息是否存在
activate redis
redis-->hrsserv: 返回token及权限信息
deactivate redis
hrsserv->hrsserv: 根据权限，执行自身业务逻辑
hrsserv-->user: 返回接口相应信息
deactivate hrsserv

@enduml
